baseurl                  = "https://oicchi-natto.github.io"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "natto-no-page"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
#googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"
#publishDir               = "docs"
[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "oicchi natto no page"

# Metadata for Open Graph and Twitter
    description          = "A new Hugo site."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "natto-no-page"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "/sample_video.mp4"
    type    = "video/mp4"
    poster  = "/background.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "posts"
    text = "ko re wa"

[[params.mainMenu]]
    link = "posts"
    text = "oicchi natto no"

[[params.mainMenu]]
    link = "posts"
    text = "page"

[[params.mainMenu]]
    link = "/daikichi-garally"
    text = "Daikichi darake"

[imaging]
    quality = 75
